test_that("internal constants are correct", {
  expect_equal(internal_RosyREDCap_token_prefix, "RosyREDCap_token_")
  expect_equal(internal_TEST_classic_token, "FAKE32TESTTOKENCLASSIC1111111111")
  expect_equal(internal_TEST_repeating_token, "FAKE32TESTTOKENREPEATING22222222")
  expect_equal(internal_TEST_longitudinal_token, "FAKE32TESTTOKENLONGITUDINAL33333")
  expect_equal(internal_TEST_multiarm_token, "FAKE32TESTTOKENMULTIARM444444444")
})
test_that("get_test_token works correctly", {
  expect_equal(get_test_token("TEST_classic"), internal_TEST_classic_token)
  expect_equal(get_test_token("TEST_repeating"), internal_TEST_repeating_token)
  expect_equal(get_test_token("TEST_longitudinal"), internal_TEST_longitudinal_token)
  expect_equal(get_test_token("TEST_multiarm"), internal_TEST_multiarm_token)
  expect_error(get_test_token("INVALID_SHORT_NAME"))
  expect_error(get_test_token(1213123))
  expect_error(get_test_token(c("TEST_classic","TEST_repeating")))
})
test_that("is_valid_REDCap_token respects the rules of 32L hexidecimal", {
  expect_true(is_valid_REDCap_token(generate_hex(32)))
  expect_false(is_valid_REDCap_token(NA))
  expect_false(is_valid_REDCap_token(NULL))
  expect_false(is_valid_REDCap_token(generate_hex(31)))
  expect_false(is_valid_REDCap_token(generate_hex(33)))
  expect_false(is_valid_REDCap_token(paste0(" ",generate_hex(31))))
  expect_false(is_valid_REDCap_token(paste0("J",generate_hex(31))))
  expect_false(is_valid_REDCap_token(paste0("_",generate_hex(31))))
  expect_false(is_valid_REDCap_token(internal_TEST_classic_token))
  expect_true(is_valid_REDCap_token(internal_TEST_classic_token,is_a_test = T))
  expect_true(is_valid_REDCap_token(internal_TEST_repeating_token,is_a_test = T))
  expect_true(is_valid_REDCap_token(internal_TEST_longitudinal_token,is_a_test = T))
  expect_true(is_valid_REDCap_token(internal_TEST_multiarm_token,is_a_test = T))
  expect_false(is_valid_REDCap_token(generate_hex(32),is_a_test = T))
  # expect_true(validate_REDCap_token(generate_hex(32)))
  # expect_error(validate_REDCap_token(generate_hex(31)))
  # expect_error(validate_REDCap_token(generate_hex(33)))
  # expect_error(validate_REDCap_token(paste0(" ",generate_hex(31))))
  # expect_error(validate_REDCap_token(paste0("J",generate_hex(31))))
  # expect_error(validate_REDCap_token(paste0("_",generate_hex(31))))
  # expect_error(validate_REDCap_token(internal_TEST_classic_token))
  # expect_no_error(validate_REDCap_token(internal_TEST_classic_token,is_a_test = T))
  # expect_no_error(validate_REDCap_token(internal_TEST_repeating_token,is_a_test = T))
  # expect_no_error(validate_REDCap_token(internal_TEST_longitudinal_token,is_a_test = T))
  # expect_no_error(validate_REDCap_token(internal_TEST_multiarm_token,is_a_test = T))
})
